"use client";

import { useEffect, useMemo, useState } from "react";

type GuestAuthResponse = {
  user_id?: string;
};

type AskResponse = {
  answer?: string;
  subject?: string;
  question?: string;
  sources?: any[];
  detail?: string; // FastAPI error payload uses "detail"
};

const API_BASE =
  process.env.NEXT_PUBLIC_API_BASE?.replace(/\/$/, "") ||
  "http://127.0.0.1:8000";

export default function Page() {
  const [userId, setUserId] = useState("demo-user");
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [lastError, setLastError] = useState<string>("");

  const canAsk = useMemo(
    () => question.trim().length > 0 && !loading,
    [question, loading]
  );

  // ✅ Create a real user_id (backend requires /auth/guest first)
  async function ensureGuestUserId(): Promise<string> {
    // If user manually typed something, still try it first.
    // If it fails with "user_id not found", we will auto-create below.
    if (userId && userId !== "demo-user") return userId;

    const res = await fetch(`${API_BASE}/auth/guest`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
    });

    const data: GuestAuthResponse = await res.json().catch(() => ({}));
    if (!res.ok || !data.user_id) {
      throw new Error(`Failed to create guest user (HTTP ${res.status})`);
    }

    setUserId(data.user_id);
    return data.user_id;
  }

  async function callAsk() {
    setLoading(true);
    setLastError("");
    setAnswer("");

    try {
      // ✅ Get valid user_id
      let uid = userId;
      if (!uid || uid === "demo-user") {
        uid = await ensureGuestUserId();
      }

      // ✅ POST /ask (your backend requires POST)
      let res = await fetch(`${API_BASE}/ask`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          user_id: uid,
          question: question.trim(),
          level: "beginner",
          style: "simple",
          context: null,
          top_k: 5,
        }),
      });

      let data: AskResponse = await res.json().catch(() => ({}));

      // ✅ If user_id is invalid, auto-create and retry once
      if (
        !res.ok &&
        typeof data?.detail === "string" &&
        data.detail.toLowerCase().includes("call /auth/guest first")
      ) {
        const newUid = await ensureGuestUserId();

        res = await fetch(`${API_BASE}/ask`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            user_id: newUid,
            question: question.trim(),
            level: "beginner",
            style: "simple",
            context: null,
            top_k: 5,
          }),
        });

        data = await res.json().catch(() => ({}));
      }

      if (!res.ok) {
        // Show FastAPI detail if present
        throw new Error(data?.detail || `HTTP ${res.status}`);
      }

      setAnswer(data.answer || "(No answer returned)");
    } catch (e: any) {
      setLastError(e?.message || "Request failed");
    } finally {
      setLoading(false);
    }
  }

  async function pingHealth() {
    setLoading(true);
    setLastError("");
    try {
      const res = await fetch(`${API_BASE}/health`);
      const text = await res.text();
      if (!res.ok) throw new Error(`Health failed: ${res.status}`);
      alert(`Backend OK:\n${text}`);
    } catch (e: any) {
      setLastError(e?.message || "Health check failed");
    } finally {
      setLoading(false);
    }
  }

  // Optional: auto-create guest id on first load
  useEffect(() => {
    (async () => {
      try {
        if (userId === "demo-user") {
          await ensureGuestUserId();
        }
      } catch {
        // ignore; user can still press Ask which will try again
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    })();
  }, []);

  return (
    <main className="min-h-screen bg-white text-black">
      <div className="max-w-3xl mx-auto px-6 py-10 space-y-6">
        <header className="space-y-2">
          <h1 className="text-3xl font-semibold">TeachAI (Python)</h1>
          <p className="text-sm text-gray-600">
            Connected to: <span className="font-mono">{API_BASE}</span>
          </p>
        </header>

        <section className="flex flex-col sm:flex-row gap-3">
          <input
            className="w-full border rounded px-3 py-2 text-sm"
            value={userId}
            onChange={(e) => setUserId(e.target.value)}
            placeholder="user_id (auto-generated by /auth/guest)"
          />
          <button
            onClick={pingHealth}
            className="border rounded px-4 py-2 text-sm hover:bg-gray-50"
            disabled={loading}
          >
            Test /health
          </button>
        </section>

        <section className="border rounded-lg p-4 space-y-3">
          <label className="text-sm font-medium">Ask a question</label>
          <textarea
            className="w-full border rounded px-3 py-2 text-sm min-h-[110px]"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Example: Explain Python lists with a small example."
          />

          <div className="flex items-center gap-3">
            <button
              onClick={callAsk}
              disabled={!canAsk}
              className="bg-black text-white rounded px-4 py-2 text-sm disabled:opacity-50"
            >
              {loading ? "Asking..." : "Ask"}
            </button>

            <button
              onClick={() => {
                setQuestion("");
                setAnswer("");
                setLastError("");
              }}
              className="border rounded px-4 py-2 text-sm hover:bg-gray-50"
              disabled={loading}
            >
              Clear
            </button>
          </div>

          {lastError && (
            <div className="text-sm text-red-600">
              Error: <span className="font-mono">{lastError}</span>
            </div>
          )}

          {answer && (
            <div className="mt-3 border rounded p-3 bg-gray-50">
              <div className="text-sm font-medium mb-2">Answer</div>
              <pre className="whitespace-pre-wrap text-sm leading-6">
                {answer}
              </pre>
            </div>
          )}
        </section>

        <footer className="text-xs text-gray-500">
          Tip: If Ask fails on deployed backend, verify Render env var
          OPENAI_API_KEY is set.
        </footer>
      </div>
    </main>
  );
}
